### ISSUE TITLE
Widget de Fechas y formato de filtrado del campo

### ISSUE THREAD

**Issue by cpasqualini** [UniversidadDelEste/OpenLex#9]
El formato de fecha con el que escribe el Widget es, por ejemplo: 25/06/2018
pero el filtro espera que sea en formato: 1963-08-28

Lo veo al intentar crear un expediente, desconozco si pasa en otros campos de fecha

**Comment by chazuttu** [comment]
No puedo encontrar el archivo en el que ocurre este problema

**Comment by Juerodriguez** [comment]
He estado viendo que este error no aparece cuando las tablas tienen los primeros datos, lo he probado instalando de nuevo el sistema, y en el sistema en cual ya tengo datos cargados me ha aparecido el siguiente error:

<class 'AttributeError'> 'NoneType' object has no attribute 'strftime'

Rastreo:

1. Traceback (most recent call last):
2.   File "/home/stylorj/PycharmProjects/Openlex/ne_web2py/web2py/gluon/restricted.py", line 219, in restricted
3.     exec(ccode, environment)
4.   File "/home/stylorj/PycharmProjects/Openlex/ne_web2py/web2py/applications/OpenLex/views/agenda/calendar.html", line 102, in <module>
5. AttributeError: 'NoneType' object has no attribute 'strftime'

Code listing:

![imagen](https://user-images.githubusercontent.com/73370773/125082476-a359f100-e09d-11eb-9aa7-abb52e3781c3.png)

**Comment by Juerodriguez** [comment]
Finalmente pude encontrar que el error se daba cuando se cargaba una agenda sin fecha de vencimiento, no se si es que sera el mismo error que marcabas @cpasqualini, si es que se resolvio se deberia cerrar esta issue.
